# 摆臂力矩仿真配置文件

# 材料参数
material:
  name: "6系铝合金"
  density: 2700  # kg/m³

# 摆杆link2参数（输入参数）
link2:
  length: 0.3    # 长度 m
  mass: 0.05     # 质量 kg

# 电机参数
motor:
  max_torque: 100.0   # 峰值扭矩 N·m (正负)
  kp: 50.0            # 位置增益
  kd: 5.0             # 速度增益
  
# 固定结构参数
base_link:
  diameter: 0.15  # m
  height: 0.06    # m

link1:
  diameter: 0.03  # m
  height: 0.08    # m
  mass: 0.5       # kg

